language: ruby
bundler_args: --without development
before_install:
   - cp config/database.travis.yml config/database.yml
before_script:
  - mysql -e 'CREATE DATABASE efg_test;'
script:
 - bundle exec rake db:create
 - bundle exec rake db:schema:load
 - bundle exec rake
rvm:
  - 1.9.3
  - 1.9.2
branches:
 only:
   - master
