development:
  adapter: mysql2
  pool: 5
  encoding: utf8
  host: localhost
  username: efg
  password: efg
  database: efg_development

test:
  adapter: mysql2
  pool: 5
  encoding: utf8
  username: efg
  password: efg
  host: localhost
  # run specs in parallel in GDS environments
  <% if ENV["FACTER_govuk_platform"].present? %>
  database: efg_test<%= ENV['TEST_ENV_NUMBER'] %>
  <% else %>
  database: efg_test
  <% end %>

# Used for data extract rake task
extract:
  adapter: sqlite3
  # If you try to run this against an NFS mounted directory, it will be slow!
  # database: /var/il0-data/efg.sqlite
  database: il0-data/efg.sqlite
