development:
  adapter: mysql2
  pool: 5
  encoding: utf8
  host: localhost
  username: efg
  password: efg
  database: efg_development

test:
  adapter: mysql2
  pool: 5
  encoding: utf8
  username: efg
  password: efg
  host: localhost
  database: efg_test
